//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProje.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUrunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUrunler()
        {
            this.TBLSatis = new HashSet<TBLSatis>();
        }
    
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public Nullable<int> UrunKategori { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string Marka { get; set; }
        public Nullable<byte> Stok { get; set; }
    
        public virtual TBLKategoriler TBLKategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSatis> TBLSatis { get; set; }
    }
}
